# Generated by Django 6.1.2 on 2026-10-09 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('summary', models.TextField(blank=True, default='')),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('product_id', models.CharField(blank=True, default='', max_length=64)),
                ('review_date', models.DateTimeField(blank=True, null=True)),
                ('sentiment', models.CharField(blank=True, choices=[('Negative', 'Negative'), ('Neutral', 'Neutral'), ('Positive', 'Positive'), ('', 'Unrated')], help_text='Derived from the rating only; empty when unrated.', max_length=16, null=True)),
                ('content_hash', models.CharField(db_index=True, editable=False, help_text='SHA-256 of product id and review text, used for duplicate detection.', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
