# Generated by Django 6.1.2 on 2026-10-09 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_predictionhistory'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['-created_at'], name='review_created_at_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['review_date'], name='review_review_date_idx'),
        ),
    ]
